// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TheScroll: typeof import('./src/components/common/TheScroll.vue')['default']
    TheTabBar: typeof import('./src/components/content/TheTabBar/TheTabBar.vue')['default']
    VanButton: typeof import("vant/es")["Button"];
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import("vant/es")["Field"];
    VanForm: typeof import("vant/es")["Form"];
    VanRate: typeof import("vant/es")["Rate"];
    VanSlider: typeof import("vant/es")["Slider"];
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}

export { }
