/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDrawerHeader: typeof import('naive-ui')['NDrawerHeader']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    Player: typeof import('./components/player/Player.vue')['default']
    PlayListDetail: typeof import('./components/playlist/PlayListDetail.vue')['default']
    PlayListState: typeof import('./components/player/PlayListState.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./components/search/SearchButton.vue')['default']
    SearchTable: typeof import('./components/search/SearchTable.vue')['default']
    SearchTableAction: typeof import('./components/search/SearchTableAction.vue')['default']
    SearchTableTitle: typeof import('./components/search/SearchTableTitle.vue')['default']
    SpottingCarousel: typeof import('./components/spotting/SpottingCarousel.vue')['default']
    SpottingImg: typeof import('./components/spotting/SpottingImg.vue')['default']
    SpottingRecommend: typeof import('./components/spotting/SpottingRecommend.vue')['default']
    TheBackground: typeof import('./components/TheBackground.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheMessage: typeof import('./components/TheMessage.vue')['default']
    TheModal: typeof import('./components/TheModal.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    ThePlayer: typeof import('./components/player/ThePlayer.vue')['default']
    TheTableAction: typeof import('./components/search/TheTableAction.vue')['default']
  }
}
